version: 2
 jobs:
   build:
     docker:
       - image: circleci/openjdk:8
     steps:
       - checkout
       - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
       - run:
        name: Hello World
          command: |
            java AC.java
